### ISSUE TITLE
Unit test test_balhistory_mintscan.TestBalHistoryMintscan gives JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by dizzib-crypto** [hodgerpodger/staketaxcsv#343]
```
dku@blockchain-cosmos src $ python -m unittest -v tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan
test_akt_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan) ... ok
test_arch_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan) ... ok
test_atom_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan) ... WARNING:root:Error on attempt 1: Expecting value: line 1 column 1 (char 0)
WARNING:root:Error on attempt 2: Expecting value: line 1 column 1 (char 0)
WARNING:root:Error on attempt 3: Expecting value: line 1 column 1 (char 0)
WARNING:root:Error on attempt 4: Expecting value: line 1 column 1 (char 0)
ERROR:root:Max retries reached. Unable to get a valid response.
ERROR:root:Unable to determine cosmos sdk version.  Returning dummy version 0.1.1.  Suggest using explicit LcdAPI like api_lcd_v1 or api_lcd_v2 instead.  
WARNING:root:Error on attempt 1: Expecting value: line 1 column 1 (char 0)
WARNING:root:Error on attempt 2: Expecting value: line 1 column 1 (char 0)
WARNING:root:Error on attempt 3: Expecting value: line 1 column 1 (char 0)
WARNING:root:Error on attempt 4: Expecting value: line 1 column 1 (char 0)
ERROR:root:Max retries reached. Unable to get a valid response.
ERROR
test_evmos_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan) ... ok
test_juno_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan) ... ok
test_osmo_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan) ... ok
test_strd_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan) ... ok
test_tia_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan) ... ok

======================================================================
ERROR: test_atom_balhistory (tests.tests.test_balhistory_mintscan.TestBalHistoryMintscan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/staketaxcsv/src/tests/tests/test_balhistory_mintscan.py", line 65, in test_atom_balhistory
    result = run_test(co.TICKER_ATOM, "cosmos1ma02nlc7lchu7caufyrrqt4r6v2mpsj92s3mw7", "2023-11-27", "2024-01-17")
  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched
    return func(*newargs, **newkeywargs)
  File "/staketaxcsv/src/tests/tests/test_balhistory_mintscan.py", line 28, in run_test
    return staketaxcsv.historical_balances(
  File "/staketaxcsv/src/staketaxcsv/api.py", line 198, in historical_balances
    bal_exporter = module.balhistory(wallet_address)
  File "/staketaxcsv/src/staketaxcsv/report_atom.py", line 84, in balhistory
    exporter = historical_balances.via_mintscan(
  File "/staketaxcsv/src/staketaxcsv/common/ibc/historical_balances.py", line 16, in via_mintscan
    bond_denom = make_lcd_api(lcd_node).get_bond_denom()
  File "/staketaxcsv/src/staketaxcsv/common/ibc/api_lcd_v1.py", line 140, in get_bond_denom
    data = self._staking_params()
  File "/staketaxcsv/src/tests/mock_lcd.py", line 32, in _staking_params
    return mock_query_one_arg(LcdAPI_v1._staking_params, self, LCDV1 + "/_staking_params/" + _clean(self.node))
  File "/staketaxcsv/src/tests/mock_query.py", line 9, in mock_query_one_arg
    return _mock_query(func, args, dirname)
  File "/staketaxcsv/src/tests/mock_query.py", line 45, in _mock_query
    data = func(*args)
  File "/staketaxcsv/src/staketaxcsv/common/ibc/api_lcd_v1.py", line 136, in _staking_params
    data = self._query(uri_path, query_params)
  File "/staketaxcsv/src/staketaxcsv/common/ibc/api_lcd_v1.py", line 28, in _query
    data = get_with_retries(self.session, url, query_params, {})
  File "/staketaxcsv/src/staketaxcsv/common/query.py", line 9, in get_with_retries
    return _make_request_with_retries(
  File "/staketaxcsv/src/staketaxcsv/common/query.py", line 25, in _make_request_with_retries
    return response.json()  # Parse and return JSON here
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 8 tests in 29.070s

FAILED (errors=1)
dku@blockchain-cosmos src $ 
```

report_atom.py also fails with the same error.

Commit [6fa45430](https://github.com/hodgerpodger/staketaxcsv/tree/6fa454302007fdf126e292950ce0069bab36b5e8)

**Comment by hodgerpodger** [comment]
Thanks for the report.  Looks like I broke the tests after changing data source from LCD to mintscan for several CSVs.  Will need a little time to rework to get tests and development smoother.

**Comment by hodgerpodger** [comment]
Fixed with https://github.com/hodgerpodger/staketaxcsv/commit/294bd853f2a09832a1970c5c6c717a5967cb4c69
